dataset: 
  raw_link: "https://github.com/trangdao909/TruckDetective/raw/main/TruckDataset_TD.zip"
  num_workers: 2
  train_path: "truck_train"
  test_path: "truck_test"

model:
  model_path: "COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml"
  ims_per_batch: 2
  base_lr: 0.00025
  max_iter: 2000
  num_classes: 1
  output_dir: "models"
  score_thresh_test: 0.5
  output_csv: res/test_result_dfw.csv

data_getter:
  top_left_position: [32.7153, -97.29733]
  bottom_right_position: [32.61464, -97.18401]
  zoom_scale: 30
  output_img_dir: "dataset/predict_img/tmp/"
  batch_img_size: 100
  saved_location: "dataset/saved_location.txt"




